services:
  db:
    image: postgres
    restart: always
    shm_size: 500mb
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - "6379:6379"


